### ISSUE TITLE
Using https prevents custom http registries from being used

### ISSUE THREAD

**Issue by luksm** [zeit/update-check#1]
https://github.com/zeit/update-check/blob/859dde951dc6177af1446f4ce9e1a5ad6e2e3893/index.js#L2

On the case the user has a private registry running on `http` only, this request will fail.

```
> hello-next@1.0.0 dev /home/user/learnnextjs-demo
> next

{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.01',
  port: 443 }
```

**Comment by luksm** [comment]
https://github.com/zeit/next.js/issues/4237 is caused by this error
